import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import productRoutes from './product.routes';
import categoryRoutes from './category.routes';
import reviewRoutes from './review.routes';
import wishlistRoutes from './wishlist.routes';
import cartRoutes from './cart.routes';
import orderRoutes from './order.routes';
import couponRoutes from './coupon.routes';
import offerRoutes from './offer.routes';
import bannerRoutes from './banner.routes';
import branchRoutes from './branch.routes';
import contactRoutes from './contact.routes';
import newsletterRoutes from './newsletter.routes';
import settingRoutes from './setting.routes';
import notificationRoutes from './notification.routes';
import analyticsRoutes from './analytics.routes';
import uploadRoutes from './upload.routes';
import postRoutes from './post.routes';
import adminUserRoutes from './adminUser.routes';
import { adminApiLimiter } from '../middlewares/rateLimiter';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users/me', userRoutes);
router.use('/products', productRoutes);
router.use('/categories', categoryRoutes);
router.use('/reviews', reviewRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/coupons', couponRoutes);
router.use('/offers', offerRoutes);
router.use('/banners', bannerRoutes);
router.use('/branches', branchRoutes);
router.use('/contacts', contactRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/settings', settingRoutes);
router.use('/notifications', notificationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/upload', uploadRoutes);
router.use('/posts', postRoutes);
router.use('/admin/users', adminApiLimiter, adminUserRoutes);

export default router;